import Head from "next/head";
import Title from "../Components/title";
import Router, { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const {
    query: { airFootprint },
  } = router;
  const props = { airFootprint };
  console.log(props.airFootprint);
  let carbonFootprint = Number(props.airFootprint);

  if (isNaN(carbonFootprint)) {
    carbonFootprint = 0;
  }

  function prevPage() {
    Router.push({
      pathname: "/air",
      query: { carbonFootprint },
    });
  }

  return (
    <>
      <Head>
        <title>Power Consumption</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="flex flex-col items-center justify-center py-5">
        <div className="p-4 flex flex w-10/12 bg-gray-100 rounded-t-xl items-center justify-center">
          <Title name="Annual Carbon Footprint" />
        </div>
        <div className="flex flex-col md:flex-row w-2/3 my-8  bg-inherit gap-2 bg-gray-50 rounded">
          <div className="w-full bg-green-700 p-8 rounded-md">
            <h2 className="text-xl text-white">Your annual Carbon Footprint</h2>
            <h1 className="text-3xl font-bold text-white mt-5">
              {carbonFootprint} <span className="text-base font-normal">C02mt</span>
            </h1>
            <button
              type="button"
              className="h-auto p-4 bg-white w-auto rounded mt-24 h-12 text-slate-700 text-sm lg:text-md font-semibold"
            >
              Offset your footprint
            </button>
          </div>
          <div className="w-full p-5 gap-2">
            <h1 className="text-green-700 font-semibold text-lg ">
              Time to Offset
            </h1>
            <p className="text-sm text-slate-500">
              A Carbon offset is a way to compensate for your carbon emissions
              by funding an equivalent carbon dioxide saving elsewhere. Our
              everyday actions consume energy and produce carbon emissions, such
              as driving, flying and heating buildings. Carbon offsetting is
              used to balance out these emissions by helping to pay for emission
              savings in other parts of the world.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
