import QuestionOne from "@/Components/questionOne";
import Results from "@/Components/results";
import Head from "next/head";
import Title from "../Components/title";
import { useState } from "react";
import Router, { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const {
    query: { retailFootprint },
  } = router;
  const props = { retailFootprint };
  console.log(props.retailFootprint);
  let oldFootprint = Number(props.retailFootprint);

  if(isNaN(oldFootprint)){
    oldFootprint = 0
  }

  const [cat, setCat] = useState(0);
  const [smallDog, setSmallDog] = useState(0);
  const [bigDog, setBigDog] = useState(0);

  const values = [cat, smallDog, bigDog];

  const petValues = values.map(function (item) {
    return Number(item);
  });

  console.log(values);
  console.log(petValues);

  const cFootprint =
    oldFootprint +
    (petValues[0] * 300 +
    petValues[1] * 730 +
    petValues[2] * 2500)/1000;
  
  const petFootprint = cFootprint.toFixed(3);

  function sendProps() {
    Router.push({
      pathname: "/land",
      query: { petFootprint },
    });
  }

  function prevPage() {
    Router.push({
      pathname:"/retail",
      query: { oldFootprint }
    });
  }

  const questions = [
    {
      id: 1,
      title: "Cats",
      name: "Cats",
      category: "Pets",
      image: "images/Pets/cat.png",
    },
    {
      id: 2,
      title: "Dogs (Under 20kg)",
      name: "Small Dog",
      category: "Pets",
      image: "images/Pets/dog.png",
    },
    {
      id: 3,
      title: "Dogs (Over 20kg)",
      name: "Big Dog",
      category: "Pets",
      image: "images/Pets/dog big.png",
    },
  ];

  return (
    <>
      <Head>
        <title>Pets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center py-5">
        <div className="p-4 flex flex w-10/12 bg-gray-100 rounded-t-xl">
          <Title name="Pet Footprint" />
        </div>
        <div className="h-20 mb-5 flex items-center justify-center w-10/12">
          <Results value={petFootprint} sendData={sendProps} goBack={prevPage} />
        </div>
        <div className="my-2 flex flex-col w-10/12">
          <div className="flex flex-wrap gap-2 justify-center overflow-y-scroll h-96 p-2">
            <QuestionOne questions={questions[0]} setValue={setCat} />
            <QuestionOne questions={questions[1]} setValue={setSmallDog} />
            <QuestionOne questions={questions[2]} setValue={setBigDog} />
          </div>
        </div>
      </main>
    </>
  );
}
